---
title: "MastersThesis"
author: "Katie Malone  17185572"
date: "7 March 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sas7bdat)
library(ggplot2)
library(dplyr)
library(tree)
library(rpart)
library(randomForest)
library(RColorBrewer) 
```

Read in data

```{r cars}
Wave3<-read.sas7bdat('Wave3.sas7bdat')
```
Change gender from 1/2 to male/female
```{r}

Wave3$gender<-ifelse(Wave3$p2sexW3=='1', 'male','female')
class(Wave3$gender)
Wave3$gender<-as.factor(Wave3$gender)
summary(Wave3$gender)

```

Investigate possible precursors for bad sleep
```{r}
#Create vector for subsetting
katie<-c(18,36,43,65,68,72,73,92,95,101,103,105,110,112,144,173,203,272,359,437,618,688,789,795,799,811,812,853,866,867,872:889,906,907,913,932:941,951:956,1011:1016,1068,1223)
length(katie)

Wave3subset<-Wave3[,katie]
glimpse(Wave3subset)
#convert numeric data to factors
katie1<-c(1:17,19:27,29,32:67)
Wave4<- Wave3subset
Wave4[,katie1]<-lapply(Wave3subset[,katie1], factor)
glimpse(Wave4)
tree<-rpart(cq3n13 ~ .,data=Wave3)
plot(tree)
text(tree, cex=.5, digits=3)

tree2<-rpart(cq3n15 ~ .,data=Wave3)
plot(tree2)
text(tree2, cex=.5, digits=3)

```


Just playing around with the data
```{r}
tree1<-randomForest(cq3n13 ~ .,data=Wave3, na.action=na.omit)
plot(tree1)
text(tree1, cex=.5, digits=3)
colnames(Wave3)
fit1<-lm(cq3n13~.,data=Wave3)
summary(Wave3$cq3k5a)
plot(Wave3$cq3k5a)

summary(Wave3$cq3n2a) # #of caffinated drinks consumed
plot(Wave3$cq3n13, Wave3$cq3n2a)#data includes outlier, need to remove
summary(Wave3$cq3n1q) # #of fizzy drinks consumed
plot(Wave3$cq3n13, Wave3$cq3n1q)

summary(Wave3$cq3m8a) # #of gp visits
plot(Wave3$cq3n13, Wave3$cq3m8a) #outliers

summary(Wave3$cq3m2) # illness
plot(Wave3$cq3n13, Wave3$cq3m2)

summary(Wave3$cq3n7) # heavy exercise
plot(Wave3$cq3n13, Wave3$cq3n7)

summary(Wave3$cq3n8) # light exercise
plot(Wave3$cq3n15, Wave3$cq3n8)


sleep1<-summarize(group_by(Wave3,cq3n15, cq3n13, gender, pc3a1),count=n())
ggplot(data=sleep1)+geom_bar(mapping=aes(x=cq3n13,y=count, fill=gender),stat='identity')

ggplot(data=sleep1)+geom_bar(mapping=aes(x=cq3n13,y=count, fill=pc3a1), stat='identity')+ scale_fill_brewer(palette = "Blues") 
Wave3$p2sexW3<-as.factor(Wave3$p2sexW3)
gender<-summarize(group_by(Wave3, p2sexW3),count=n())
sleep1<-summarize(group_by(Wave3, cq3n15, p2sexW3, cq3n13),count=n())
sleep2<-summarize(group_by(Wave3, cq3n16a, cq3n16b,cq3n16c,cq3n16d,cq3n16e, cq3n16f, p2sexW3),count=n())
ggplot(data=sleep1)+geom_bar(mapping=aes(x=cq3n15, y=count, fill=p2sexW3),stat='identity')
ggplot(data=sleep1)+geom_col(mapping=aes( x=cq3n13, y=count, fill=p2sexW3), stat='identity', position='dodge')
plot(gender)
plot(sleep2)
sleep2
ggplot(data=sleep2)+geom_bar(mapping=aes(x=cq3n16a, y=count, fill=p2sexW3),stat='identity')
ggplot(data=sleep2)+geom_bar(mapping=aes(x=x, y=count, fill=p2sexW3),stat='identity')
x<-c(sleep2$cq3n16a, sleep2$cq3n16b, sleep2$cq3n16c, sleep2$cq3n16d)
x
ggplot(data=Wave3)+geom_histogram(mapping=aes( x=cq3n13, colo))+facet_wrap(~p2sexW3)
```

